os: linux
dist: xenial
language: node_js
jobs:
  include:
  - os: linux
    node_js: 12
  - os: osx
    node_js: 12
addons:
  chrome: stable
  firefox: latest
services:
- xvfb
script:
- npm run ci
before_deploy:
- sed -i 's/"private":\ true/"private":\ false/' package.json
- sed -i -E 's/^dist\/?.*$//' .gitignore
deploy:
  provider: npm
  edge: true
  email:
    secure: "vFku2HASiG87+c4zdfjnMgNzDm6olPOUG5fgN3NcfRP2/vZLuT2l1M3OaZ94DGaTTEJ7slFfoBRCoYJ3o0N2AEHTFo52XtTE8cN2T9rdbUZ9O7fskRFipiM6xGF6WZHFBdslBCrPGor60IRKeUh5yxa8L9+iJlCBiKVb9rGpPEAWaW0/tYh99pu1S+oMuyaiYw6/HvpXR6VmzYcnj7ky4J8XRcyENuFY5tPbCZ09CAlDmRjivTvfT9BgGMXViOgNtDXPP2+g1cbGnSsAf6Yo2Zy8/Ax38hnqW8fft7bI3/fCEbUQeNW2tc6jxjRigJ6AXssmoRAD9LmLw5cwsLx05EN2Blm+rSiZ84hR8O4pj55Nw0itAQLrFTAQ6oVPdIcEy2xtO2OHxcW0WMvVL6FhR38Ik2vOZY/wKTHyCxHF1YQXFLSfS0+QqxYC4KlcybWtSHjwjBdJto4y2jenNno+Ge1TJI1mHHRIuFig4oVzxnVl48CNoR6u8y/cNnZKovbHLefMBNi8usJQj6620CUd8uTk1Q4EfIM7xaq4Gitt0YhzRK63JqjwG/gDu5421FdyATqd3GMb9DHK1YqHgA2PJLf5ODSSFAGCBZTulWJpcnqaKijpjWCBb8PEeS7rBYBDvEHWMwaENpJxPODvztsQXyOFfiPhRp9r8BL2graGQoo="
  api_token:
    secure: "SA1pmp0yte5Gnqyxgp9xbX2HbO/wZ9vpDMn1vpsPUsRT6v1Z9HVmHHQW6atiaH6okYKXIfF3WerwbNEQr82CRbLPVo5TWlT/rDIsfqdJXQNNQD2zSAKIECoWC1nCN1LRzFOjEiXl6UFjLicE3Oe5DB37dv+JQYI/i6vllE3yNLxqNDvx/U+YiEKzVpZGd4i5+pMzeBvc6e0KKxkmJjm3Uh1Spuxf8s6oXSKMUsZeMUUq92+/mB2ZvN3VEqiCL8JNB+3UBNDp/vMG+HxPIjgZaze+/lrY3uryBhRdqfkY3+UCh8m9QZi1ESnfRFDlvHR4w1A+2kw06FSucljRlTGh6UuMevA6YlSqedF1JEAV4nuJURMAb0U8aMVA2uqSoS5mGtjPWbREUzEQ8EPkacBYmQe+WvSmKlAg2mY+VXdphdcFeJPdX5npX6U54k3ZgyjTAChxaPBWOW4e2CkY5Y1Kv249nlmcULNbBoZqiEkoLwogu+zpQDri7+Ebyy428zxkeg+z3BYBRD76dLl0GuQYGejORLanIvwa0SuEFe0GRs6YhHhUnLa22Rqt3AK+qH+3mAlfVsjXLg16DhD/KpGvWi7RMoHHsjruIv68ZAwDGG1PMD+KkSy0mi9cliZOJrXko8JwOj13bIu5RcSmisX1KAtJLLnYUr+b35hkiqJWSto="
  on:
    node_js: 12
    condition:
    - $TRAVIS_BRANCH = master
    - $TRAVIS_EVENT_TYPE = push
    - $TRAVIS_COMMIT_MESSAGE =~ ^v[0-9]+(\.[0-9]+)*($|\n)
    - $TRAVIS_OS_NAME = linux
notifications:
  email:
    recipients:
    - secure: "vFku2HASiG87+c4zdfjnMgNzDm6olPOUG5fgN3NcfRP2/vZLuT2l1M3OaZ94DGaTTEJ7slFfoBRCoYJ3o0N2AEHTFo52XtTE8cN2T9rdbUZ9O7fskRFipiM6xGF6WZHFBdslBCrPGor60IRKeUh5yxa8L9+iJlCBiKVb9rGpPEAWaW0/tYh99pu1S+oMuyaiYw6/HvpXR6VmzYcnj7ky4J8XRcyENuFY5tPbCZ09CAlDmRjivTvfT9BgGMXViOgNtDXPP2+g1cbGnSsAf6Yo2Zy8/Ax38hnqW8fft7bI3/fCEbUQeNW2tc6jxjRigJ6AXssmoRAD9LmLw5cwsLx05EN2Blm+rSiZ84hR8O4pj55Nw0itAQLrFTAQ6oVPdIcEy2xtO2OHxcW0WMvVL6FhR38Ik2vOZY/wKTHyCxHF1YQXFLSfS0+QqxYC4KlcybWtSHjwjBdJto4y2jenNno+Ge1TJI1mHHRIuFig4oVzxnVl48CNoR6u8y/cNnZKovbHLefMBNi8usJQj6620CUd8uTk1Q4EfIM7xaq4Gitt0YhzRK63JqjwG/gDu5421FdyATqd3GMb9DHK1YqHgA2PJLf5ODSSFAGCBZTulWJpcnqaKijpjWCBb8PEeS7rBYBDvEHWMwaENpJxPODvztsQXyOFfiPhRp9r8BL2graGQoo="
    on_success: change
    on_failure: always
after_script:
- |
  if
    [ $TRAVIS_BRANCH == "master" ]
    [ $TRAVIS_EVENT_TYPE == "push" ]
    [ $TRAVIS_OS_NAME == "linux" ]
    [ $ENCRYPTION_LABEL ]
  then :; else exit 0; fi
- eval `ssh-agent -s`
- openssl aes-256-cbc -K `eval echo $\{${ENCRYPTION_LABEL}_key\}` -iv `eval echo $\{${ENCRYPTION_LABEL}_iv\}` -in .travis/deploy_key.enc -d | ssh-add -
- gulp site
- mkdir ../gh-pages
- cp -rf ./gh-pages ../
- cat package.json | json version
- new_version=$(cat package.json | json version)
- git reset --hard HEAD~
- cat package.json | json version
- old_version=$(cat package.json | json version)
- git reset --hard ORIG_HEAD
- node -e 'if (!require("semver").gt(process.argv[1], process.argv[2])) process.exit(1)' $new_version $old_version || exit 0
- git fetch origin gh-pages:gh-pages
- git checkout --orphan gh-pages
- git checkout -m gh-pages
- ls -a | grep -vE "^.git$|^\.+$" | xargs rm -rf
- cp -rf ../gh-pages/* ./
- find | grep -vE "^./.git(/|$)"
- sed -i 's|\(baseurl:\s\+\)|\1//falsandtru.github.io|' _config.yml
- git add -A
- git commit -m "Update web contents" --author "Travis-CI"
- git push git@github.com:${TRAVIS_REPO_SLUG} gh-pages:gh-pages
